// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VoteSvc.Data;

#nullable disable

namespace VoteSvc.Data.Migrations
{
    [DbContext(typeof(VoteDbContext))]
    partial class VoteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VoteSvc.Models.Vote", b =>
                {
                    b.Property<Guid>("VoterId")
                        .HasColumnType("uuid")
                        .HasColumnName("voter_id");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .HasColumnType("text")
                        .HasColumnName("target_type");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("VoterId", "TargetId", "TargetType")
                        .HasName("pk_votes");

                    b.HasIndex("TargetId", "TargetType")
                        .HasDatabaseName("ix_votes_target_id_target_type");

                    b.ToTable("votes", null, t =>
                        {
                            t.HasCheckConstraint("ck_vote_target_type", "target_type IN ('Question', 'Answer')");

                            t.HasCheckConstraint("ck_vote_value", "value IN (1, -1)");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
